version: 2.1
parameters:
    pEnabled:
      default: false
      type: boolean
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  approve-merge-pr:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Create pull request"
          command: |
            git remote add origin https://lixxia1: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@github.com/lixxia1/STPWLF-TEST.git
            git checkout main
            git merge --no-ff -m "Merge new-branch into master" test-branch-1
#       - run:
#           name: Merge pull request
#           command: |
#             git remote add origin https://lixxia1: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@github.com/lixxia1/STPWLF-TEST.git
#             git fetch origin
#             git checkout master
#             git pull origin master
#             git merge --no-ff -m "Merge new-branch into master" new-branch
#             git push origin master
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
