version: 2.1
parameters:
    pEnabled:
      default: false
      type: boolean
jobs:
  approve-merge-pr:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Create pull request"
          command: |
            git checkout main
            git merge --no-ff -m "Merge test-branch-1 into master" origin/test-branch-1
#       - run:
#           name: Merge pull request
#           command: |
#             git fetch origin
#             git checkout master
#             git pull origin master
#             git merge --no-ff -m "Merge new-branch into master" new-branch
#             git push origin master
workflows:
  merge-pr:
    jobs:
      - approve-merge-pr
