version: 2.1
parameters:
    pEnabled:
      default: false
      type: boolean
jobs:
  approve-merge-pr:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Create Changelog File"
          command: |
            echo "Steppenwolf ui clone release"
      - gh/install
      - run:
          name: "Create pull request"
          command: |
            gh pr create --reviewer lixxia1 --base main --head origin/test-branch-1 --title "test branch pr" --body "test branch pr body description"
            
workflows:
  merge-pr:
    jobs:
      - approve-merge-pr
