version: 2.1
parameters:
    pEnabled:
      default: false
      type: boolean
orbs:
  gh: circleci/github-cli@2.0
jobs:
  approve-merge-pr:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh/setup
      - run:
          name: "Create pull request"
          command: |
            gh pr create --reviewer lixxia1 --base test-branch-1 --head test-branch-2 --title "test branch pr" --body "test branch pr body description"
#        Github token configured in environmental variables within circleci project settings
workflows:
  merge-pr:
    jobs:
      - approve-merge-pr
